### ISSUE TITLE
Foreign key constraints

### ISSUE THREAD

**Issue by Misosooup** [masom/lhm_php#18]
Hey @masom,

Everything works fine until CI errors out with foreign key issues. When a table is renamed, all foreign keys get renamed as well which makes sense if running it from a MySQL command.

I am just wondering if LHM supports renaming those foreign keys that has been updated to point to `lhma_blah`? Or should this be a manual process in the migration such that we have to identify which tables are referencing the changed table and update them manually.

P.S. I don't use github much other than downloading packages via composer. So I do not know if there is any process that I should be following here.

**Comment by masom** [comment]
The upstream project has the same limitation but there might be a way around this.

See https://github.com/soundcloud/lhm/issues/34

**Comment by Misosooup** [comment]
Thanks.
