### ISSUE TITLE
Suggest Phinx

### ISSUE THREAD

**Issue by shadowhand** [masom/lhm_php#6]
Right now composer only use `robmorgan/phinx` for `require-dev`, but I suspect you probably want to use LHM with Phinx:

```
"suggest": {
    "robmorgan/phinx": "Advanced database migration tool"
},
```

**Comment by masom** [comment]
Good idea, will be added tomorrow.

**Comment by masom** [comment]
Added in https://github.com/masom/lhm_php/commit/58d966fb4938784f089a09a7dadd780b81b9d337
